/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\AAAAA\\vue\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-82b5c472",
    path: "/book/JVM/JVM%E7%9A%84%E7%BB%84%E6%88%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82b5c472").then(next)
    },
  },
  {
    path: "/book/JVM/JVM的组成.html",
    redirect: "/book/JVM/JVM%E7%9A%84%E7%BB%84%E6%88%90.html"
  },
  {
    path: "/book/JVM/JVM的组成.html",
    redirect: "/book/JVM/JVM%E7%9A%84%E7%BB%84%E6%88%90.html"
  },
  {
    name: "v-11a1be79",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11a1be79").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-024b5f3c",
    path: "/book/Java%E5%9F%BA%E7%A1%80/String.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-024b5f3c").then(next)
    },
  },
  {
    path: "/book/Java基础/String.html",
    redirect: "/book/Java%E5%9F%BA%E7%A1%80/String.html"
  },
  {
    path: "/book/Java基础/String.html",
    redirect: "/book/Java%E5%9F%BA%E7%A1%80/String.html"
  },
  {
    name: "v-43f16930",
    path: "/book/Java%E5%9F%BA%E7%A1%80/StringUtils.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43f16930").then(next)
    },
  },
  {
    path: "/book/Java基础/StringUtils.html",
    redirect: "/book/Java%E5%9F%BA%E7%A1%80/StringUtils.html"
  },
  {
    path: "/book/Java基础/StringUtils.html",
    redirect: "/book/Java%E5%9F%BA%E7%A1%80/StringUtils.html"
  },
  {
    name: "v-513a3884",
    path: "/book/Java%E5%9F%BA%E7%A1%80/%E5%AD%97%E8%8A%82%E7%A0%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-513a3884").then(next)
    },
  },
  {
    path: "/book/Java基础/字节码.html",
    redirect: "/book/Java%E5%9F%BA%E7%A1%80/%E5%AD%97%E8%8A%82%E7%A0%81.html"
  },
  {
    path: "/book/Java基础/字节码.html",
    redirect: "/book/Java%E5%9F%BA%E7%A1%80/%E5%AD%97%E8%8A%82%E7%A0%81.html"
  },
  {
    name: "v-7ca8caad",
    path: "/book/Java%E5%9F%BA%E7%A1%80/%E6%8B%86%E7%AE%B1%E4%B8%8E%E8%A3%85%E7%AE%B1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ca8caad").then(next)
    },
  },
  {
    path: "/book/Java基础/拆箱与装箱.html",
    redirect: "/book/Java%E5%9F%BA%E7%A1%80/%E6%8B%86%E7%AE%B1%E4%B8%8E%E8%A3%85%E7%AE%B1.html"
  },
  {
    path: "/book/Java基础/拆箱与装箱.html",
    redirect: "/book/Java%E5%9F%BA%E7%A1%80/%E6%8B%86%E7%AE%B1%E4%B8%8E%E8%A3%85%E7%AE%B1.html"
  },
  {
    name: "v-667d0662",
    path: "/book/MQ/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-667d0662").then(next)
    },
  },
  {
    name: "v-0ed8eec5",
    path: "/book/%E5%88%86%E5%B8%83%E5%BC%8F/distributeSystem.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ed8eec5").then(next)
    },
  },
  {
    path: "/book/分布式/distributeSystem.html",
    redirect: "/book/%E5%88%86%E5%B8%83%E5%BC%8F/distributeSystem.html"
  },
  {
    path: "/book/分布式/distributeSystem.html",
    redirect: "/book/%E5%88%86%E5%B8%83%E5%BC%8F/distributeSystem.html"
  },
  {
    name: "v-8f031744",
    path: "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/javabasic.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8f031744").then(next)
    },
  },
  {
    path: "/book/小技巧/javabasic.html",
    redirect: "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/javabasic.html"
  },
  {
    path: "/book/小技巧/javabasic.html",
    redirect: "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/javabasic.html"
  },
  {
    name: "v-51a085e9",
    path: "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/Java8%20Stream.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51a085e9").then(next)
    },
  },
  {
    path: "/book/小技巧/Java8 Stream.html",
    redirect: "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/Java8%20Stream.html"
  },
  {
    path: "/book/小技巧/Java8 Stream.html",
    redirect: "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/Java8%20Stream.html"
  },
  {
    name: "v-df128ec4",
    path: "/book/%E5%B9%B6%E5%8F%91/countdownlatch.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df128ec4").then(next)
    },
  },
  {
    path: "/book/并发/countdownlatch.html",
    redirect: "/book/%E5%B9%B6%E5%8F%91/countdownlatch.html"
  },
  {
    path: "/book/并发/countdownlatch.html",
    redirect: "/book/%E5%B9%B6%E5%8F%91/countdownlatch.html"
  },
  {
    name: "v-406b31a6",
    path: "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-406b31a6").then(next)
    },
  },
  {
    path: "/book/微服务/SpringCloud.html",
    redirect: "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud.html"
  },
  {
    path: "/book/微服务/SpringCloud.html",
    redirect: "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud.html"
  },
  {
    name: "v-e3fb5ec0",
    path: "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud%E9%A1%B9%E7%9B%AE%E6%90%AD%E5%BB%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e3fb5ec0").then(next)
    },
  },
  {
    path: "/book/微服务/SpringCloud项目搭建.html",
    redirect: "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud%E9%A1%B9%E7%9B%AE%E6%90%AD%E5%BB%BA.html"
  },
  {
    path: "/book/微服务/SpringCloud项目搭建.html",
    redirect: "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud%E9%A1%B9%E7%9B%AE%E6%90%AD%E5%BB%BA.html"
  },
  {
    name: "v-3c94f6ef",
    path: "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c94f6ef").then(next)
    },
  },
  {
    path: "/book/数据库/mysql.html",
    redirect: "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html"
  },
  {
    path: "/book/数据库/mysql.html",
    redirect: "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html"
  },
  {
    name: "v-99471b44",
    path: "/book/%E6%A1%86%E6%9E%B6/Mybatis-plus.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-99471b44").then(next)
    },
  },
  {
    path: "/book/框架/Mybatis-plus.html",
    redirect: "/book/%E6%A1%86%E6%9E%B6/Mybatis-plus.html"
  },
  {
    path: "/book/框架/Mybatis-plus.html",
    redirect: "/book/%E6%A1%86%E6%9E%B6/Mybatis-plus.html"
  },
  {
    name: "v-34535ca8",
    path: "/book/%E6%A1%86%E6%9E%B6/Spring.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34535ca8").then(next)
    },
  },
  {
    path: "/book/框架/Spring.html",
    redirect: "/book/%E6%A1%86%E6%9E%B6/Spring.html"
  },
  {
    path: "/book/框架/Spring.html",
    redirect: "/book/%E6%A1%86%E6%9E%B6/Spring.html"
  },
  {
    name: "v-65a2d1aa",
    path: "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/%E7%B4%A2%E5%BC%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65a2d1aa").then(next)
    },
  },
  {
    path: "/book/数据库/索引.html",
    redirect: "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/%E7%B4%A2%E5%BC%95.html"
  },
  {
    path: "/book/数据库/索引.html",
    redirect: "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/%E7%B4%A2%E5%BC%95.html"
  },
  {
    name: "v-161b3d18",
    path: "/book/%E6%A1%86%E6%9E%B6/SpringCloud.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-161b3d18").then(next)
    },
  },
  {
    path: "/book/框架/SpringCloud.html",
    redirect: "/book/%E6%A1%86%E6%9E%B6/SpringCloud.html"
  },
  {
    path: "/book/框架/SpringCloud.html",
    redirect: "/book/%E6%A1%86%E6%9E%B6/SpringCloud.html"
  },
  {
    name: "v-0de0e3dc",
    path: "/book/%E9%9B%86%E5%90%88/List.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0de0e3dc").then(next)
    },
  },
  {
    path: "/book/集合/List.html",
    redirect: "/book/%E9%9B%86%E5%90%88/List.html"
  },
  {
    path: "/book/集合/List.html",
    redirect: "/book/%E9%9B%86%E5%90%88/List.html"
  },
  {
    name: "v-1c084634",
    path: "/book/%E9%9B%86%E5%90%88/Map.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c084634").then(next)
    },
  },
  {
    path: "/book/集合/Map.html",
    redirect: "/book/%E9%9B%86%E5%90%88/Map.html"
  },
  {
    path: "/book/集合/Map.html",
    redirect: "/book/%E9%9B%86%E5%90%88/Map.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]