/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Yan-sir",
  "description": "个人网站",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "JVM的组成",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/JVM/JVM%E7%9A%84%E7%BB%84%E6%88%90.html",
      "relativePath": "book/JVM/JVM的组成.md",
      "key": "v-82b5c472",
      "path": "/book/JVM/JVM%E7%9A%84%E7%BB%84%E6%88%90.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-11a1be79",
      "path": "/"
    },
    {
      "title": "String",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-01T00:00:00.000Z",
        "category": [
          "Java基础"
        ],
        "tag": [
          "red",
          "big",
          "round"
        ]
      },
      "regularPath": "/book/Java%E5%9F%BA%E7%A1%80/String.html",
      "relativePath": "book/Java基础/String.md",
      "key": "v-024b5f3c",
      "path": "/book/Java%E5%9F%BA%E7%A1%80/String.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "StringUtils",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-02T00:00:00.000Z",
        "category": [
          "Java基础"
        ],
        "tag": [
          "red",
          "big",
          "round"
        ],
        "star": true
      },
      "regularPath": "/book/Java%E5%9F%BA%E7%A1%80/StringUtils.html",
      "relativePath": "book/Java基础/StringUtils.md",
      "key": "v-43f16930",
      "path": "/book/Java%E5%9F%BA%E7%A1%80/StringUtils.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ],
      "excerpt": "<h1 id=\"stringutils\"><a class=\"header-anchor\" href=\"#stringutils\">#</a> StringUtils</h1>\n<p>A apple article being stared.</p>\n"
    },
    {
      "title": "字节码",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-04T00:00:00.000Z",
        "category": [
          "Java基础",
          "Fruit"
        ],
        "tag": [
          "red",
          "big",
          "round"
        ]
      },
      "regularPath": "/book/Java%E5%9F%BA%E7%A1%80/%E5%AD%97%E8%8A%82%E7%A0%81.html",
      "relativePath": "book/Java基础/字节码.md",
      "key": "v-513a3884",
      "path": "/book/Java%E5%9F%BA%E7%A1%80/%E5%AD%97%E8%8A%82%E7%A0%81.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "拆箱与装箱",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-03T00:00:00.000Z",
        "category": [
          "Java基础",
          "Fruit"
        ],
        "tag": [
          "red",
          "big",
          "round"
        ]
      },
      "regularPath": "/book/Java%E5%9F%BA%E7%A1%80/%E6%8B%86%E7%AE%B1%E4%B8%8E%E8%A3%85%E7%AE%B1.html",
      "relativePath": "book/Java基础/拆箱与装箱.md",
      "key": "v-7ca8caad",
      "path": "/book/Java%E5%9F%BA%E7%A1%80/%E6%8B%86%E7%AE%B1%E4%B8%8E%E8%A3%85%E7%AE%B1.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "MQ的使用",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2024-8-19",
        "category": [
          "集合",
          "Fruit"
        ],
        "tag": [
          "yellow",
          "curly",
          "long"
        ]
      },
      "regularPath": "/book/MQ/1.html",
      "relativePath": "book/MQ/1.md",
      "key": "v-667d0662",
      "path": "/book/MQ/1.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "分布式系统构建",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E5%88%86%E5%B8%83%E5%BC%8F/distributeSystem.html",
      "relativePath": "book/分布式/distributeSystem.md",
      "key": "v-0ed8eec5",
      "path": "/book/%E5%88%86%E5%B8%83%E5%BC%8F/distributeSystem.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Java开发小技巧",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/javabasic.html",
      "relativePath": "book/小技巧/javabasic.md",
      "key": "v-8f031744",
      "path": "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/javabasic.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "linux常用命令",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/Java8%20Stream.html",
      "relativePath": "book/小技巧/Java8 Stream.md",
      "key": "v-51a085e9",
      "path": "/book/%E5%B0%8F%E6%8A%80%E5%B7%A7/Java8%20Stream.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Countdownlatch的使用",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E5%B9%B6%E5%8F%91/countdownlatch.html",
      "relativePath": "book/并发/countdownlatch.md",
      "key": "v-df128ec4",
      "path": "/book/%E5%B9%B6%E5%8F%91/countdownlatch.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Springcloud",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud.html",
      "relativePath": "book/微服务/SpringCloud.md",
      "key": "v-406b31a6",
      "path": "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Springcloud",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud%E9%A1%B9%E7%9B%AE%E6%90%AD%E5%BB%BA.html",
      "relativePath": "book/微服务/SpringCloud项目搭建.md",
      "key": "v-e3fb5ec0",
      "path": "/book/%E5%BE%AE%E6%9C%8D%E5%8A%A1/SpringCloud%E9%A1%B9%E7%9B%AE%E6%90%AD%E5%BB%BA.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Mysql",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html",
      "relativePath": "book/数据库/mysql.md",
      "key": "v-3c94f6ef",
      "path": "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/mysql.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Mybatis-plus的使用",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-11T00:00:00.000Z",
        "category": [
          "Fruit",
          "Strawberry"
        ],
        "tag": [
          "red",
          "small"
        ]
      },
      "regularPath": "/book/%E6%A1%86%E6%9E%B6/Mybatis-plus.html",
      "relativePath": "book/框架/Mybatis-plus.md",
      "key": "v-99471b44",
      "path": "/book/%E6%A1%86%E6%9E%B6/Mybatis-plus.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Spring",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E6%A1%86%E6%9E%B6/Spring.html",
      "relativePath": "book/框架/Spring.md",
      "key": "v-34535ca8",
      "path": "/book/%E6%A1%86%E6%9E%B6/Spring.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Mysql",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/%E7%B4%A2%E5%BC%95.html",
      "relativePath": "book/数据库/索引.md",
      "key": "v-65a2d1aa",
      "path": "/book/%E6%95%B0%E6%8D%AE%E5%BA%93/%E7%B4%A2%E5%BC%95.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "SpringCloud微服务项目构建",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-10T00:00:00.000Z",
        "category": [
          "Dragon Fruit",
          "Fruit"
        ],
        "tag": [
          "red",
          "big"
        ]
      },
      "regularPath": "/book/%E6%A1%86%E6%9E%B6/SpringCloud.html",
      "relativePath": "book/框架/SpringCloud.md",
      "key": "v-161b3d18",
      "path": "/book/%E6%A1%86%E6%9E%B6/SpringCloud.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "List中ArrayList和LinkedList的区别",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-09T00:00:00.000Z",
        "category": [
          "Cherry"
        ],
        "tag": [
          "red",
          "small",
          "round"
        ]
      },
      "regularPath": "/book/%E9%9B%86%E5%90%88/List.html",
      "relativePath": "book/集合/List.md",
      "key": "v-0de0e3dc",
      "path": "/book/%E9%9B%86%E5%90%88/List.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "title": "Map",
      "frontmatter": {
        "icon": "pen-to-square",
        "date": "2022-01-07T00:00:00.000Z",
        "category": [
          "Banana"
        ],
        "tag": [
          "yellow",
          "curly",
          "long"
        ]
      },
      "regularPath": "/book/%E9%9B%86%E5%90%88/Map.html",
      "relativePath": "book/集合/Map.md",
      "key": "v-1c084634",
      "path": "/book/%E9%9B%86%E5%90%88/Map.html",
      "headers": [
        {
          "level": 2,
          "title": "Heading 2",
          "slug": "heading-2"
        },
        {
          "level": 3,
          "title": "Heading 3",
          "slug": "heading-3"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "JAVADOC",
        "link": "/java/",
        "items": [
          {
            "text": "Java基础",
            "link": "/"
          },
          {
            "text": "集合",
            "link": "/"
          },
          {
            "text": "并发",
            "link": "/"
          },
          {
            "text": "框架",
            "link": "/"
          },
          {
            "text": "数据库",
            "link": "/"
          },
          {
            "text": "linux",
            "link": "/"
          },
          {
            "text": "JVM",
            "link": "/"
          },
          {
            "text": "分布式",
            "link": "/"
          },
          {
            "text": "微服务",
            "link": "/"
          },
          {
            "text": "MQ",
            "link": "/"
          }
        ]
      },
      {
        "text": "书籍",
        "link": "/books/"
      }
    ],
    "sidebar": [
      {
        "title": "Java基础",
        "collapsable": false,
        "children": [
          {
            "title": "拆箱与装箱",
            "path": "/book/Java基础/拆箱与装箱"
          },
          {
            "title": "字节码",
            "path": "/book/Java基础/字节码"
          },
          {
            "title": "String",
            "path": "/book/Java基础/String"
          },
          {
            "title": "StringUtils",
            "path": "/book/Java基础/StringUtils"
          }
        ]
      },
      {
        "title": "集合",
        "collapsable": false,
        "children": [
          {
            "title": "List",
            "path": "/book/集合/List"
          },
          {
            "title": "Map",
            "path": "/book/集合/Map"
          }
        ]
      },
      {
        "title": "框架",
        "collapsable": false,
        "children": [
          {
            "title": "Mybatis-plus",
            "path": "/book/框架/Mybatis-plus"
          },
          {
            "title": "Spring",
            "path": "/book/框架/Spring"
          },
          {
            "title": "SpringCloud",
            "path": "/book/框架/SpringCloud"
          }
        ]
      },
      {
        "title": "并发",
        "collapsable": false,
        "children": [
          {
            "title": "countdownlatch",
            "path": "/book/并发/countdownlatch"
          }
        ]
      },
      {
        "title": "JVM",
        "collapsable": false,
        "children": [
          {
            "title": "JVM的组成",
            "path": "/book/JVM/JVM的组成"
          }
        ]
      },
      {
        "title": "数据库",
        "collapsable": false,
        "children": [
          {
            "title": "List",
            "path": "/book/数据库/List"
          },
          {
            "title": "Map",
            "path": "/book/数据库/Map"
          }
        ]
      },
      {
        "title": "分布式",
        "collapsable": false,
        "children": [
          {
            "title": "mysql",
            "path": "/book/分布式/mysql"
          },
          {
            "title": "索引",
            "path": "/book/分布式/索引"
          }
        ]
      },
      {
        "title": "微服务",
        "collapsable": false,
        "children": [
          {
            "title": "SpringCloud",
            "path": "/book/微服务/SpringCloud"
          },
          {
            "title": "SpringCloud项目搭建",
            "path": "/book/微服务/SpringCloud项目搭建"
          }
        ]
      },
      {
        "title": "linux",
        "collapsable": false,
        "children": [
          {
            "title": "List",
            "path": "/book/linux/List"
          },
          {
            "title": "Map",
            "path": "/book/linux/Map"
          }
        ]
      },
      {
        "title": "MQ",
        "collapsable": false,
        "children": [
          {
            "title": "List",
            "path": "/book/MQ/List"
          },
          {
            "title": "Map",
            "path": "/book/MQ/Map"
          }
        ]
      }
    ]
  }
}